import type { TournamentTypes, Tournament } from "../types/tournaments.types";

export const initialTournaments: Record<TournamentTypes, Tournament> = {
  "premier-league": {
    type: "premier-league",
    name: "Premier League",
    participants: [],
    matches: [],
    showDraws: true,
    showMatches: true,
    showWinLossIcons: false,
    isParticipantAPlayer: false,
    isAMatch: false,
    iconName: "",
    showActionForms: true,
  },
  eurobasket: {
    type: "eurobasket",
    name: "EuroBasket",
    participants: [],
    matches: [],
    showDraws: true,
    showMatches: false,
    showWinLossIcons: false,
    showActionForms: false,
    isParticipantAPlayer: false,
    isAMatch: true,
    iconName: "basketball",
  },
  wimbledon: {
    type: "wimbledon",
    name: "Wimbledon",
    participants: [],
    matches: [],
    showDraws: true,
    showMatches: true,
    showWinLossIcons: true,
    showActionForms: true,
    isParticipantAPlayer: true,
    isAMatch: true,
    iconName: "tennis",
  },
};
